### ISSUE TITLE
DBProxy在ubuntu安装失败

### ISSUE THREAD

**Issue by hylaz** [Meituan-Dianping/DBProxy#25]
ubuntu版本为16.04.
在make编译的时候编译出错，不知道是否支持ubuntu现阶段！

**Comment by tsthght** [comment]
目前DBProxy只在CentOS6.5 上进行过适配，系统版本和依赖库版本详见：https://github.com/Meituan-Dianping/DBProxy/blob/master/doc/QUICK_START.md。

**Comment by jixianliang** [comment]
文档已经提交，代码目前提交到了子分支 https://github.com/jixianliang/DBProxy ，后续周五(2017.01.20)会合并到主分支。
