### ISSUE TITLE
希望提供debian系的安装方法啊

### ISSUE THREAD

**Issue by arnolix** [Meituan-Dianping/DBProxy#30]
目前debian系 在国内服务器端 还是挺广泛的，建议整个debian系的安装方法，谢谢~！

**Comment by rj03hou** [comment]
你有尝试在的debian下编译安装吗？编译安装的方法应该是一致的。

**Comment by coco101000000000** [comment]
ubuntu 国内使用率也是很高  麻烦 支持一下ubuntu ，刚才试了一下依赖 很多ubuntu上没有

**Comment by tsthght** [comment]
ubuntu:14.04版本我们已经编译、安装运行通过了，整理后会立即将 编译 方法提交到github~

**Comment by coco101000000000** [comment]
thanks

**Comment by jixianliang** [comment]
文档已经提交，代码目前提交到了子分支 https://github.com/jixianliang/DBProxy ，后续会合并到主分支。
