### ISSUE TITLE
QUICK_START.md里面的安装依赖

### ISSUE THREAD

**Issue by jianqingdu** [Meituan-Dianping/DBProxy#45]
需要添加libevent-devel openssl-devel, 不然会找不到这些库

**Comment by rj03hou** [comment]
你的是centos7吗？

**Comment by jianqingdu** [comment]
是的，centos7

**Comment by rj03hou** [comment]
已经在https://github.com/Meituan-Dianping/DBProxy/blob/master/doc/QUICK_START.md中增加这两个包。
