### ISSUE TITLE
发现俩个地方有点问题

### ISSUE THREAD

**Issue by arnolix** [Meituan-Dianping/DBProxy#60]
1. set names utf8 collate utf8_unicode_ci;   设置该字符集报错
2. Exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[07000]: <<Unknown error>>: 1105 Proxy Warning - Syntax Forbidden Prepare:select * from `pt_client` where `pt_client`.`id` = ? limit 1 (SQL: select * from `pt_client` where `pt_client`.`id` = 8005 limit 1)'     在执行语句时候出错

**Comment by arnolix** [comment]
这俩个问题， 改框架都已经ok了

**Comment by sky-L** [comment]
怎么改的啊？

**Comment by sky-L** [comment]
Prepare 这个需要改什么地方呢

**Comment by sky-L** [comment]
设置  PDO::ATTR_EMULATE_PREPARES => true  可以解决 prepare 的问题
